name: iOS Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build app
      run: |
        xcodebuild -project iOSStreamingApp.xcodeproj -scheme iOSStreamingApp -sdk iphoneos -configuration Release clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

    - name: Archive app
      run: |
        xcodebuild -project iOSStreamingApp.xcodeproj -scheme iOSStreamingApp -sdk iphoneos -configuration Release archive -archivePath ${{ github.workspace }}/build/iOSStreamingApp.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

    - name: Export IPA
      run: |
        xcodebuild -exportArchive -archivePath ${{ github.workspace }}/build/iOSStreamingApp.xcarchive -exportPath ${{ github.workspace }}/build/ipa -exportOptionsPlist ExportOptions.plist

- name: Upload artifact
   uses: actions/upload-artifact@v4
  with:
    name: my-artifact
    path: path/to/artifact

